"""Initial sync with Vultr

Revision ID: 6effdc38b31a
Revises: 
Create Date: 2026-01-09 16:01:07.994204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6effdc38b31a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('note_body', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_tbl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deadlines_tbl')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('department_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('members_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.drop_column('member_id')

    with op.batch_alter_table('prev_date_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('prev_date_list_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'deadlines', ['deadlines_id'], ['id'])
        batch_op.drop_column('prev_date_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project_manager_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('project_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('project_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('project_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'deadlines', ['deadlines_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'members', ['project_manager_id'], ['id'])
        batch_op.drop_column('p_members_id')
        batch_op.drop_column('project_manager')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('project_members_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['id'])
        batch_op.drop_column('p_members_id')
        batch_op.drop_column('removed_date')
        batch_op.drop_column('re_assigned_date')

    with op.batch_alter_table('sub_task_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('sub_task_list_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task_tbl', ['parent_task_id'], ['id'])
        batch_op.drop_column('notes_id')
        batch_op.drop_column('generated_code')
        batch_op.drop_column('checked_timestamp')
        batch_op.drop_column('created_on')
        batch_op.drop_column('sub_task_id')

    with op.batch_alter_table('task_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('task_tbl_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('task_tbl_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('task_tbl_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_members', ['p_members_id'], ['id'])
        batch_op.create_foreign_key(None, 'deadlines', ['deadline_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('notes_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('progress')
        batch_op.drop_column('generated_code')
        batch_op.drop_column('task_id')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('task_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('generated_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('progress', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('priority', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_tbl_ibfk_1'), 'deadlines_tbl', ['deadline_id'], ['deadlines_id'])
        batch_op.create_foreign_key(batch_op.f('task_tbl_ibfk_2'), 'project', ['project_id'], ['project_id'])
        batch_op.create_foreign_key(batch_op.f('task_tbl_ibfk_3'), 'project_members', ['p_members_id'], ['p_members_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('sub_task_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_task_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_on', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('checked_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('generated_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sub_task_list_ibfk_1'), 'task_tbl', ['parent_task_id'], ['task_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('re_assigned_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('removed_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('p_members_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_members_ibfk_1'), 'members', ['member_id'], ['member_id'])
        batch_op.drop_column('project_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('project_manager', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('p_members_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_ibfk_1'), 'department', ['department_id'], ['department_id'])
        batch_op.create_foreign_key(batch_op.f('project_ibfk_3'), 'deadlines_tbl', ['deadlines_id'], ['deadlines_id'])
        batch_op.create_foreign_key(batch_op.f('project_ibfk_2'), 'members', ['project_manager'], ['member_id'])
        batch_op.drop_column('project_manager_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('prev_date_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_date_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prev_date_list_ibfk_1'), 'deadlines_tbl', ['deadlines_id'], ['deadlines_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('members_ibfk_1'), 'department', ['department_id'], ['department_id'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.create_table('deadlines_tbl',
    sa.Column('deadlines_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('create_on', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('deadlines_id')
    )
    op.drop_table('notes_tbl')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
