"""intial migration

Revision ID: f4b8015ed881
Revises: 
Create Date: 2026-01-12 15:02:11.592302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4b8015ed881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=255), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('notes_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'])
        batch_op.drop_column('pin_datetime')
        batch_op.drop_column('reply_code')
        batch_op.drop_column('edited_on')
        batch_op.drop_column('pin_stat')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'members', ['project_manager'], ['member_id'])

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'])
        batch_op.drop_column('removed_date')
        batch_op.drop_column('re_assigned_date')

    with op.batch_alter_table('sub_task_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'notes_tbl', ['notes_id'], ['notes_id'])
        batch_op.drop_column('checked_timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('generated_code')

    with op.batch_alter_table('task_tbl', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'notes_tbl', ['notes_id'], ['notes_id'])
        batch_op.drop_column('progress')
        batch_op.drop_column('generated_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('progress', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sub_task_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('checked_timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('re_assigned_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('removed_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notes_tbl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_stat', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('edited_on', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reply_code', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('pin_datetime', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_id')

    op.drop_table('members')
    # ### end Alembic commands ###
